- request:
    body: null
    headers: !!python/object:requests.structures.CaseInsensitiveDict
      _store:
        accept: !!python/tuple [accept, application/json]
        accept-encoding: !!python/tuple [Accept-Encoding, 'gzip, deflate, compress']
        authorization: !!python/tuple [Authorization, !!python/unicode 'Basic cXhSU05jSWRlQToxZjBBVkNaUEpiUm5kRjlGTlNHTU9XTWZIOUtNVURhWA==']
        cache-control: !!python/tuple [cache-control, no-cache]
        content-length: !!python/tuple [content-length, '0']
        content-type: !!python/tuple [content-type, application/json]
        user-agent: !!python/tuple [user-agent, myfc_id client]
    method: GET
    url: /organizations/api/accounts/00000000-0000-0000-0000-000000000000/
  response:
    body: {string: '"Account 00000000-0000-0000-0000-000000000000 has no relation
        with service identity_client"'}
    headers: {allow: 'GET, PUT, HEAD, OPTIONS', connection: keep-alive, content-length: '91',
      content-type: application/json, date: 'Tue, 25 Jun 2013 22:34:55 GMT', p3p: CP="NON
        DSP COR CURa TIA", server: nginx/0.7.67, vary: 'Authenticate, Accept'}
    status: {code: 404, message: NOT FOUND}
